### ISSUE TITLE
Does getRelatedListRecords support manual or automatic refresh?

### ISSUE THREAD

**Issue by banderson-stripe** [pozil/ui-api-playground#10]
https://github.com/pozil/ui-api-playground/blob/c7079f2eb6a636aedc84cceabf6d6de608e9db75/src/main/default/lwc/getRelatedListRecords/getRelatedListRecords.js#L2

I am trying insert Contact Records against an Account record using the builtin `createRecord` wire method. However, I am not seeing the `getRelatedListRecords` wire method get updated with the new Contact records.

How do I force or tell the Lightning Data Service (LDS) that new Contact records are on the related Account list.

**Comment by banderson-stripe** [comment]
@pozil I have. I have tried passing through both the Contact Ids and Account Ids but I don't see any updates. I also have a stackexchange post here https://salesforce.stackexchange.com/questions/381144/force-refresh-of-getrelatedlistrecords?noredirect=1#comment552084_381144

**Comment by pozil** [comment]
Ok, I'll do a bit of research and chime in on SFSE. I'll close this issue for now.

**Comment by shalletantony** [comment]
Hi .. I am working on a LWC with inlineEdit on related List for custom components. somehow my code is not returning any records.
Do u have any idea how can we use in custom object and relationships.
